CREATE VIEW Top_Taged AS
SELECT TAG_PHOTO_ID, CT
FROM (SELECT TAG_PHOTO_ID, COUNT(TAG_SUBJECT_ID) AS CT
	  FROM jiaqni.PUBLIC_Tags
	  GROUP BY TAG_PHOTO_ID
	  ORDER BY COUNT(TAG_SUBJECT_ID) DESC, TAG_PHOTO_ID ASC)
WHERE ROWNUM <= 5;


SELECT TT.TAG_PHOTO_ID, P.PHOTO_LINK, P.ALBUM_ID, A.ALBUM_NAME, U.USER_ID, U.FIRST_NAME, U.LAST_NAME, TT.CT
FROM Top_Taged TT
LEFT JOIN jiaqni.PUBLIC_Tags T ON TT.TAG_PHOTO_ID = T.TAG_PHOTO_ID
LEFT JOIN jiaqni.PUBLIC_Users U ON U.USER_ID = T.TAG_SUBJECT_ID
LEFT JOIN jiaqni.PUBLIC_Photos P ON T.TAG_PHOTO_ID = P.PHOTO_ID
LEFT JOIN jiaqni.PUBLIC_Albums A ON P.ALBUM_ID = A.ALBUM_ID
ORDER BY TT.CT DESC, T.TAG_PHOTO_ID ASC, U.USER_ID ASC;

-- SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME
-- FROM jiaqni.PUBLIC_Tags P, jiaqni.PUBLIC_Users U
-- WHERE *** = P.PHOTO_ID AND U.USER_ID = P.TAG_SUBJECT_ID
-- ORDER BY U.USER_ID ASC;

-- SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME
-- FROM Top_Taged T, jiaqni.PUBLIC_Tags P, jiaqni.PUBLIC_Users U
-- WHERE T.TAG_PHOTO_ID = P.PHOTO_ID AND U.USER_ID = P.TAG_SUBJECT_ID
-- ORDER BY U.USER_ID ASC;


DROP VIEW Top_Taged;

-- SELECT T.TAG_PHOTO_ID, P.PHOTO_LINK, P.ALBUM_ID, A.ALBUM_NAME
-- FROM Top_Taged T, jiaqni.PUBLIC_Photos P, jiaqni.PUBLIC_Albums A
-- WHERE T.TAG_PHOTO_ID = P.PHOTO_ID AND P.ALBUM_ID = A.ALBUM_ID;



