CREATE VIEW Friend_List AS
SELECT F.USER2_ID AS USER_ID
FROM Friends F
WHERE F.USER1_ID = 200002
UNION
SELECT F.USER1_ID AS USER_ID
FROM Friends F
WHERE F.USER2_ID = 200002
MINUS 
SELECT U.USER_ID
FROM Users U
WHERE U.YEAR_OF_BIRTH IS NULL 
OR U.MONTH_OF_BIRTH IS NULL
OR U.DAY_OF_BIRTH IS NULL;


SELECT USER_ID, FIRST_NAME, LAST_NAME
FROM Users
WHERE USER_ID = 
(SELECT * FROM (SELECT FL.USER_ID 
				FROM Friend_List FL, Users U
				WHERE FL.USER_ID = U.USER_ID
				ORDER BY U.YEAR_OF_BIRTH DESC, U.MONTH_OF_BIRTH DESC, U.DAY_OF_BIRTH DESC, FL.USER_ID DESC)
WHERE ROWNUM = 1);


SELECT USER_ID, FIRST_NAME, LAST_NAME
FROM Users
WHERE USER_ID = 
(SELECT * FROM (SELECT FL.USER_ID 
				FROM Friend_List FL, Users U
				WHERE FL.USER_ID = U.USER_ID
				ORDER BY U.YEAR_OF_BIRTH ASC, U.MONTH_OF_BIRTH ASC, U.DAY_OF_BIRTH ASC, FL.USER_ID DESC)
WHERE ROWNUM = 1);


DROP VIEW Friend_List;