SELECT C.STATE_NAME, COUNT(E.EVENT_ID)
FROM jiaqni.PUBLIC_User_Events E
LEFT JOIN jiaqni.PUBLIC_Cities C
ON E.EVENT_CITY_ID = C.CITY_ID
GROUP BY C.STATE_NAME
HAVING COUNT(E.EVENT_ID) = (SELECT MAX(COUNT(E1.EVENT_ID)) FROM jiaqni.PUBLIC_User_Events E1
							LEFT JOIN jiaqni.PUBLIC_Cities C1
							ON E1.EVENT_CITY_ID = C1.CITY_ID
							GROUP BY C1.STATE_NAME)
ORDER BY C.STATE_NAME ASC;