ELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME
FROM Users U
WHERE U.USER_ID IN 
(SELECT UC.USER_ID
FROM User_Current_Cities UC
JOIN User_Hometown_Cities UH
ON UC.USER_ID = UH.USER_ID
WHERE UC.CURRENT_CITY_ID <> UH.HOMETOWN_CITY_ID)
ORDER BY U.USER_ID ASC;