SELECT F.USER1_ID, F.USER2_ID, U1.First_Name, U1.Last_Name, U2.First_Name, U2.Last_Name
FROM jiaqni.PUBLIC_Users U1, jiaqni.PUBLIC_Users U2, jiaqni.PUBLIC_Friends F, 
	 jiaqni.PUBLIC_User_Hometown_City H1, jiaqni.PUBLIC_User_Hometown_City H2
WHERE U1.YEAR_OF_BIRTH IS NOT NULL AND U2.YEAR_OF_BIRTH IS NOT NULL AND
U1.USER_ID = H1.USER_ID AND U2.USER_ID = H2.USER_ID
AND H1.HOMETOWN_CITY_ID = H2.HOMETOWN_CITY_ID
AND U1.USER_ID = F.USER1_ID AND U2.USER_ID = F.USER2_ID
AND U1.LAST_NAME = U2.LAST_NAME
AND ABS(U1.YEAR_OF_BIRTH - U2.YEAR_OF_BIRTH) < 10
ORDER BY F.USER1_ID ASC, F.USER2_ID ASC;