SELECT U.USER_ID, U.FIRST_NAME, U.LAST_NAME
FROM jiaqni.PUBLIC_Users U
WHERE U.USER_ID IN 
(SELECT UC.USER_ID
FROM jiaqni.PUBLIC_User_Current_City UC
JOIN jiaqni.PUBLIC_User_Hometown_City UH
ON UC.USER_ID = UH.USER_ID
WHERE UC.CURRENT_CITY_ID <> UH.HOMETOWN_CITY_ID)
ORDER BY U.USER_ID ASC;