CREATE VIEW Top_Taged AS
SELECT TAG_PHOTO_ID, CT
FROM (SELECT TAG_PHOTO_ID, COUNT(TAG_SUBJECT_ID) AS CT
	  FROM Tags
	  GROUP BY TAG_PHOTO_ID
	  ORDER BY COUNT(TAG_SUBJECT_ID) DESC, TAG_PHOTO_ID ASC)
WHERE ROWNUM <= 5;


SELECT TT.TAG_PHOTO_ID, P.PHOTO_LINK, P.ALBUM_ID, A.ALBUM_NAME, U.USER_ID, U.FIRST_NAME, U.LAST_NAME, TT.CT
FROM Top_Taged TT
LEFT JOIN Tags T ON TT.TAG_PHOTO_ID = T.TAG_PHOTO_ID
LEFT JOIN Users U ON U.USER_ID = T.TAG_SUBJECT_ID
LEFT JOIN Photos P ON T.TAG_PHOTO_ID = P.PHOTO_ID
LEFT JOIN Albums A ON P.ALBUM_ID = A.ALBUM_ID
ORDER BY TT.CT DESC, T.TAG_PHOTO_ID ASC, U.USER_ID ASC;

